plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xtractmobile'
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.xtractmobile"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("../my-release-key.jks")
            storePassword "XnM3G-9u"
            keyAlias "my-key-alias"
            keyPassword "XnM3G-9u"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    // Add any other dependencies your app needs
}
